### ISSUE TITLE
publish artifacts to maven

### ISSUE THREAD

**Issue by dmichel1** [lightstep/lightstep-census-java#1]
Hi,

Would it be possible to have these build artifacts published to maven central? I did some local testing with this library and it seems to working as expected, I can see my opencensus traces in Lightstep!

Thanks

**Comment by carlosalberto** [comment]
Hey @dmichel1 this is published now: https://search.maven.org/search?q=g:com.lightstep.opencensus

;)

**Comment by dmichel1** [comment]
@carlosalberto thank you! confirmed everything is working.
