### ISSUE TITLE
Shutdown example?

### ISSUE THREAD

**Issue by walles** [lightstep/lightstep-census-java#12]
Hi!

I tried to make a simple example just creating an exporter, making an OpenCensus span and reporting it.

It didn't work until I added a number of `Thread.sleep()` statements around my code.

Could you please add to the README a simple example that:
* Sets up a working environment
* Starts / finishes an OpenCensus span
* Flushes outstanding data to the satellite(s)
* Shuts down
* After shutdown has actually reported the span so that it can be seen in your web UI

In my experiments neither `LightStepTraceExporter.unregister()` nor `JRETracer.flush()`, nor a combination thereof seem to actually flush data to your satellites, but `Thread.sleep(20000)` does.

  Regards /Johan

**Comment by carlosalberto** [comment]
So `flush()` should be enough, we might need to dig on this (I know it _did_ help a few users who needed it, so we might need to do extra work there). Besides that, you could call `Tracer.close()` as well (but probably you did, with the same results?)

**Comment by walles** [comment]
I never did try `Tracer.close()`.

If you could do some experimentation and then update the docs (and / or the library itself), that would be super!

**Comment by walles** [comment]
@carlosalberto would it be possible for you to document how to shut down correctly?

**Comment by malafeev** [comment]
I created [example](https://github.com/lightstep/lightstep-census-java/tree/master/example)
No any trace is lost.
I will update README also soon.

**Comment by walles** [comment]
@malafeev, your example doesn't use `LightStepTraceExporter.unregister()`:

<https://github.com/lightstep/lightstep-census-java/blob/1adae83380b0173681e7f3ce9c128f4779347460/src/main/java/com/lightstep/opencensus/exporter/LightStepTraceExporter.java#L51>

What's the intended use for that method? Should it just be removed from the public API?

**Comment by walles** [comment]
Another question:

This solved my shutdown problems (yay for documentation!), but I'm getting this at the end:
```
[Main.main()] DEBUG com.lightstep.tracer.jre.JRETracer - Sending report, 7 spans
[Main.main()] DEBUG com.lightstep.tracer.jre.JRETracer - Report sent successfully (7 spans)
[Main.main()] INFO com.lightstep.tracer.jre.JRETracer - Disabling client library
[
lightDstoenp-e,r exeamine tphortei ngre-sult htehrree:a dh]t WARNt pcso:m/./ligahtstpepp..tlriacgehrt.sjtreep..JcRoEmT/rsapcoetri f- Exceptyio/ns ertvriycien-gd irectto solreepy /isnptraci ngrep-orjtavian/go ptehratiroensad

[lightstep-reporting-thread] DEBUG com.lightstep.tracer.jre.JRETracer - Reporting thread stopped
```

Do you get the gibberish part of the logs as well before `Reporting thread stopped`?

**Comment by malafeev** [comment]
At least `public static void unregister()` is required if you want to register another exporter.

What I see:
```
DEBUG   2020-03-13 20:31:30,829 [main] com.lightstep.tracer.jre.JRETracer  - Sending report, 11 spans
DEBUG   2020-03-13 20:31:30,829 [lightstep-reporting-thread] com.lightstep.tracer.jre.JRETracer  - Next report: 1584102691288 (464.748761) [0]
DEBUG   2020-03-13 20:31:30,902 [main] com.lightstep.tracer.jre.JRETracer  - Report sent successfully (11 spans)
INFO    2020-03-13 20:31:30,902 [main] com.lightstep.tracer.jre.JRETracer  - Disabling client library
WARN    2020-03-13 20:31:30,903 [lightstep-reporting-thread] com.lightstep.tracer.jre.JRETracer  - Exception trying to sleep in reporting thread
DEBUG   2020-03-13 20:31:30,903 [lightstep-reporting-thread] com.lightstep.tracer.jre.JRETracer  - Reporting thread stopped
```
I think it's encoding issue. This warning can be ignored, it means that `Thread.sleep()` is interrupted.

**Comment by malafeev** [comment]
@walles can this issue be closed now? example is added, README is updated for shutdown.

**Comment by walles** [comment]
It's beautiful, thank you @malafeev! :)
