### ISSUE TITLE
java.lang.IllegalStateException: LightStep exporter is not registered.

### ISSUE THREAD

**Issue by walles** [lightstep/lightstep-census-java#13]
I'm using this together with <https://github.com/lightstep/lightstep-tracer-java-common>.

With this in my pom...
```
    <dependency>
      <groupId>com.lightstep.tracer</groupId>
      <artifactId>tracer-okhttp</artifactId>
      <version>0.20.0</version>
    </dependency>
```

... I get this when calling `LightStepTraceExporter.unregister()`:
```
java.lang.IllegalStateException: LightStep exporter is not registered.
	at com.lightstep.opencensus.exporter.LightStepTraceExporter.unregister(LightStepTraceExporter.java:54)
```

With `tracer-okhttp` `0.19.3`, the same code works fine.

Is `LightStepTraceExporter.unregister()` working for you with `tracer-okhttp` 0.20.0?

This is somewhat related to #12, since shutting down isn't really documented.

**Comment by malafeev** [comment]
@walles I created [example](https://github.com/lightstep/lightstep-census-java/tree/master/example)
but I couldn't reproduce your issue.

**Comment by walles** [comment]
I ran into unrelated problems trying to re-repro this, I'll close this for now and re-open in case this turns out to still be crashing for me. Thanks for the example @malafeev!
