### ISSUE TITLE
Census message_events do not show up properly in LightStep

### ISSUE THREAD

**Issue by sbaum1994** [lightstep/lightstep-census-java#5]
Looks like something might be going on with this code [line](https://github.com/lightstep/lightstep-census-java/blob/242e2894b6a871c8a45750bc5efe57d8f2da9b29/src/main/java/com/lightstep/opencensus/exporter/LightStepExporterHandler.java#L94)

In LightStep the logs do not show up for the compressed sizes of the message, instead it just says "RECEIVED RECEIVED SENT SENT"

[message events in opencensus](https://opencensus.io/tracing/span/time_events/message_event/#1)

**Comment by marcusb** [comment]
Same goes for [annotations](https://opencensus.io/tracing/span/time_events/annotation/). The description text shows up, but not the attributes.

**Comment by malafeev** [comment]
@sbaum1994 @marcusb please look at #6

**Comment by malafeev** [comment]
@carlosalberto please release a new version

**Comment by malafeev** [comment]
please try version 0.0.3 with a fix.

**Comment by marcusb** [comment]
It works, seeing the attributes in LightStep now. Thanks for fixing!
