### ISSUE TITLE
Compilation error due to 1.6 syntax error

### ISSUE THREAD

**Issue by carlosalberto** [lightstep/lightstep-census-java#8]
I'm getting this error while building:

> lightstep-census-java/src/main/java/com/lightstep/opencensus/exporter/LightStepExporterHandler.java:[92,52] diamond operator is not supported in -source 1.6

Once this is solved, we can publish to Maven Central ;)

**Comment by carlosalberto** [comment]
@malafeev ^

**Comment by malafeev** [comment]
@carlosalberto fixed
please release a new version
